import {initializeApp} from "https://www.gstatic.com/firebasejs/12.3.0/firebase-app.js";
import {getAuth,createUserWithEmailAndPassword,signInWithEmailAndPassword,onAuthStateChanged,signOut,updateProfile} from "https://www.gstatic.com/firebasejs/12.3.0/firebase-auth.js";
import {getFirestore,collection,doc,setDoc,addDoc,query,orderBy,onSnapshot,serverTimestamp,getDoc,limit,getDocs,where} from "https://www.gstatic.com/firebasejs/12.3.0/firebase-firestore.js";
import {firebaseConfig} from "./firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
let authMode="login",currentRoom=null,unMsg=null,unMembers=null,unDm=null,selectedCategory="Chill",mediaStream=null,dmPeer=null;
const nameOf=u=>(u?.displayName||"vibes User").trim(), initials=n=>(n||"vibes").split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase();
const safe=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const toast=t=>{const x=$("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1800)};
const catIcon=c=>({Chill:"🌙",Music:"🎵",Games:"🎮",Chat:"💬"}[c]||"🎉");
function go(id){document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active-page",p.id===id));document.querySelectorAll(".nav-item").forEach(n=>n.classList.toggle("active",n.dataset.page===id));scrollTo(0,0)}
function refresh(){const u=auth.currentUser,n=nameOf(u),i=initials(n);["homeUsername","profileUsername"].forEach(id=>$(id).textContent=n);$("profileNameInput").value=n;$("profileAvatar").textContent=i;$("topProfileBtn").textContent=i;$("profileEmail").textContent="Email private"}
function openCreate(){$("createModal").classList.remove("hidden");$("newRoomName").focus()}

document.querySelectorAll(".auth-tab").forEach(b=>b.onclick=()=>{authMode=b.dataset.authTab;document.querySelectorAll(".auth-tab").forEach(x=>x.classList.toggle("active",x===b));$("signupFields").classList.toggle("hidden",authMode!=="signup");$("authBtn").textContent=authMode==="signup"?"Create account":"Login"});
$("authBtn").onclick=async()=>{const e=$("email").value.trim(),p=$("password").value,n=$("username").value.trim();if(!e||!p)return $("authStatus").textContent="Enter email and password.";if(authMode==="signup"&&n.length<3)return $("authStatus").textContent="Username must be 3+ characters.";try{if(authMode==="signup"){const c=await createUserWithEmailAndPassword(auth,e,p);await updateProfile(c.user,{displayName:n});await setDoc(doc(db,"profiles",c.user.uid),{username:n,bio:"",gender:"",createdAt:serverTimestamp()},{merge:true})}else await signInWithEmailAndPassword(auth,e,p)}catch(x){$("authStatus").textContent=x.message.replace("Firebase: ","")}};
onAuthStateChanged(auth,async u=>{const ok=!!u;$("authView").classList.toggle("hidden",ok);$("appView").classList.toggle("hidden",!ok);if(!u)return;refresh();await loadProfile();loadRooms()});
async function loadProfile(){try{const s=await getDoc(doc(db,"profiles",auth.currentUser.uid));if(s.exists()){const p=s.data();$("bioInput").value=p.bio||"";$("genderInput").value=p.gender||"";$("profileNameInput").value=p.username||nameOf(auth.currentUser)}}catch(e){console.warn(e)}}
$("saveProfileBtn").onclick=async()=>{const n=$("profileNameInput").value.trim(),bio=$("bioInput").value.trim(),gender=$("genderInput").value;if(n.length<3)return toast("Username must be 3+ characters");try{await updateProfile(auth.currentUser,{displayName:n});await setDoc(doc(db,"profiles",auth.currentUser.uid),{username:n,bio,gender,updatedAt:serverTimestamp()},{merge:true});refresh();toast("Profile saved")}catch(e){toast(e.message)}};
document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>go(b.dataset.page));$("topProfileBtn").onclick=()=>go("profilePage");$("quickCreate").onclick=openCreate;$("roomsCreateBtn").onclick=openCreate;$("navCreate").onclick=openCreate;$("seeAllRooms").onclick=()=>go("roomsPage");$("quickGames").onclick=()=>go("gamesPage");$("quickMusic").onclick=()=>go("musicPage");
$("quickJoin").onclick=()=>{const c=prompt("Enter room code");if(c)joinRoom(c.trim().toUpperCase())};$("closeModal").onclick=()=>$("createModal").classList.add("hidden");
document.querySelectorAll(".category").forEach(b=>b.onclick=()=>{selectedCategory=b.dataset.category;document.querySelectorAll(".category").forEach(x=>x.classList.toggle("active",x===b))});
$("createRoomBtn").onclick=async()=>{const title=$("newRoomName").value.trim()||"My Party",id=Math.random().toString(36).slice(2,8).toUpperCase();try{await setDoc(doc(db,"rooms",id),{ownerId:auth.currentUser.uid,ownerName:nameOf(auth.currentUser),title,category:selectedCategory,createdAt:serverTimestamp()});$("createModal").classList.add("hidden");await joinRoom(id);toast("Party created")}catch(e){$("roomStatus").textContent=e.message}};
function renderRooms(el,rooms){if(!rooms.length){el.innerHTML='<div class="empty-state"><h3>No rooms yet</h3><p>Create the first party.</p></div>';return}el.innerHTML=rooms.map(r=>`<article class="room-card"><div class="room-card-top"><div class="room-icon">${catIcon(r.category)}</div><div style="flex:1"><h3>${safe(r.title||".vibes")}</h3><p>${safe(r.category||"Chat")} · ${safe(r.ownerName||"vibes User")}</p></div></div><button class="join-btn" data-room="${safe(r.id)}">Join · ${safe(r.id)}</button></article>`).join("");el.querySelectorAll(".join-btn").forEach(b=>b.onclick=()=>joinRoom(b.dataset.room))}
function loadRooms(){const q=query(collection(db,"rooms"),orderBy("createdAt","desc"),limit(20));onSnapshot(q,s=>{const r=s.docs.map(d=>({id:d.id,...d.data()}));renderRooms($("homeRooms"),r.slice(0,4));renderRooms($("roomsList"),r)},e=>console.error(e))}
async function joinRoom(id){try{const r=await getDoc(doc(db,"rooms",id));if(!r.exists())return toast("Room not found");const d=r.data();currentRoom=id;await setDoc(doc(db,"rooms",id,"members",auth.currentUser.uid),{uid:auth.currentUser.uid,username:nameOf(auth.currentUser),joinedAt:serverTimestamp()},{merge:true});$("roomTitle").textContent=d.title||"Room";$("roomCodeLabel").textContent=id;$("roomHostLabel").textContent=`Hosted by ${d.ownerName||"vibes User"} · ${d.category||"Chat"}`;go("roomPage");unMsg?.();unMembers?.();unMsg=onSnapshot(query(collection(db,"rooms",id,"messages"),orderBy("createdAt"),limit(100)),s=>{const box=$("messages");box.innerHTML="";s.forEach(x=>{const m=x.data();const e=document.createElement("div");e.className="msg";e.innerHTML=`<b>${safe(m.username||"User")}</b><span>${safe(m.text||"")}</span>`;box.appendChild(e)});box.scrollTop=box.scrollHeight});unMembers=onSnapshot(collection(db,"rooms",id,"members"),s=>{$("roomOnlineCount").textContent=`● ${s.size} online`;$('members').innerHTML=s.docs.map(x=>{const n=x.data().username||"User";return `<div class="member"><span class="member-avatar">${initials(n)}</span><div><b>${safe(n)}</b></div></div>`}).join("")})}catch(e){toast(e.message)}}
$("sendBtn").onclick=sendRoomMsg;$("messageInput").onkeydown=e=>e.key==="Enter"&&sendRoomMsg();async function sendRoomMsg(){const t=$("messageInput").value.trim();if(!t||!currentRoom)return;await addDoc(collection(db,"rooms",currentRoom,"messages"),{uid:auth.currentUser.uid,username:nameOf(auth.currentUser),text:t,createdAt:serverTimestamp()});$("messageInput").value=""}
$("backHomeBtn").onclick=()=>go("homePage");$("leaveRoomBtn").onclick=()=>{unMsg?.();unMembers?.();currentRoom=null;go("homePage")};$("copyRoomBtn").onclick=async()=>{try{await navigator.clipboard.writeText(currentRoom);toast("Room code copied")}catch{toast(currentRoom)}};
// Private messages
function convId(a,b){return [a,b].sort().join("_")}
$("openDmBtn").onclick=async()=>{const id=$("dmUserId").value.trim();if(!id||id===auth.currentUser.uid)return toast("Enter your friend's UID");openDm(id)};
async function openDm(peer){dmPeer=peer;$("dmPanel").classList.remove("hidden");$("dmTitle").textContent="Private chat · "+peer.slice(0,8);unDm?.();const cid=convId(auth.currentUser.uid,peer);unDm=onSnapshot(query(collection(db,"dms",cid,"messages"),orderBy("createdAt"),limit(100)),s=>{const b=$("dmMessages");b.innerHTML="";s.forEach(x=>{const m=x.data(),e=document.createElement("div");e.className="msg "+(m.from===auth.currentUser.uid?"mine":"");e.innerHTML=`<b>${m.from===auth.currentUser.uid?"You":"Friend"}</b><span>${safe(m.text)}</span>`;b.appendChild(e)});b.scrollTop=b.scrollHeight})}
$("closeDmBtn").onclick=()=>{$("dmPanel").classList.add("hidden");unDm?.();dmPeer=null};$("dmSendBtn").onclick=sendDm;$("dmInput").onkeydown=e=>e.key==="Enter"&&sendDm();async function sendDm(){const t=$("dmInput").value.trim();if(!t||!dmPeer)return;await addDoc(collection(db,"dms",convId(auth.currentUser.uid,dmPeer),"messages"),{from:auth.currentUser.uid,to:dmPeer,text:t,createdAt:serverTimestamp()});$("dmInput").value=""}
// Music
$("loadMusicBtn").onclick=()=>{const u=$("audioUrl").value.trim();if(!u)return toast("Enter a direct audio URL");$("audioPlayer").src=u;$("musicTitle").textContent=$("audioTitle").value.trim()||"Playing track";$("audioPlayer").play().catch(()=>toast("Tap play to start audio"))};
// Games
let gameUnsub=null;document.querySelectorAll(".game-card").forEach(b=>b.onclick=()=>openGame(b.dataset.game));function openGame(g){const p=$("gamePanel");if(g==="dice"){p.innerHTML='<h3>🎲 Dice</h3><p>Roll your dice.</p><button id="rollBtn" class="primary-btn">Roll</button><div id="rollResult" class="game-result">—</div>';$("rollBtn").onclick=()=>$("rollResult").textContent="You rolled "+(Math.floor(Math.random()*6)+1)}else if(g==="guess"){p.innerHTML='<h3>🔢 Number Guess</h3><p>Guess 1–10.</p><input id="guessInput" type="number" min="1" max="10"><button id="guessBtn" class="primary-btn">Guess</button><div id="guessResult" class="game-result"></div>';const n=Math.floor(Math.random()*10)+1;$("guessBtn").onclick=()=>$("guessResult").textContent=+$("guessInput").value===n?"Correct! 🎉":"Try again."}else{if(!currentRoom)return p.innerHTML='<h3>⭕ Tic-Tac-Toe</h3><p>Join a room first, then open the game.</p>';const ref=doc(db,"rooms",currentRoom,"games","ttt");setDoc(ref,{board:["","","","","","","","",""],turn:"X",winner:"",updatedAt:serverTimestamp()},{merge:true});gameUnsub?.();gameUnsub=onSnapshot(ref,s=>renderTTT(s.exists()?s.data():{}));}}
function renderTTT(g){const p=$("gamePanel");p.innerHTML='<h3>⭕ Tic-Tac-Toe</h3><p id="turnText"></p><div class="ttt" id="tttBoard">'+Array.from({length:9},(_,i)=>`<button data-i="${i}">${safe(g.board?.[i]||"")}</button>`).join("")+'</div><button id="resetTtt" class="outline-btn">Reset</button>';$("turnText").textContent=g.winner?`Winner: ${g.winner}`:`Turn: ${g.turn||"X"}`;document.querySelectorAll("#tttBoard button").forEach(b=>b.onclick=()=>moveTTT(+b.dataset.i,g));$("resetTtt").onclick=()=>setDoc(doc(db,"rooms",currentRoom,"games","ttt"),{board:Array(9).fill(""),turn:"X",winner:"",updatedAt:serverTimestamp()})}
async function moveTTT(i,g){if(g.winner||g.board?.[i])return;const board=[...(g.board||Array(9).fill(""))];board[i]=g.turn||"X";const lines=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];let w="";for(const [a,b,c] of lines)if(board[a]&&board[a]===board[b]&&board[a]===board[c])w=board[a];const next=(g.turn||"X")==="X"?"O":"X";await setDoc(doc(db,"rooms",currentRoom,"games","ttt"),{board,turn:next,winner:w,updatedAt:serverTimestamp()},{merge:true})}
// microphone local permission
$("micBtn").onclick=async()=>{try{if(mediaStream){mediaStream.getTracks().forEach(t=>t.stop());mediaStream=null;$("micBtn").textContent="🎙 Mic";return}mediaStream=await navigator.mediaDevices.getUserMedia({audio:true});$("micBtn").textContent="🔴 Mic on";toast("Microphone enabled on this device")}catch(e){toast("Microphone permission was denied")}};
$("logoutBtn").onclick=async()=>{unMsg?.();unMembers?.();unDm?.();if(mediaStream)mediaStream.getTracks().forEach(t=>t.stop());await signOut(auth)};
