import {initializeApp} from 'https://www.gstatic.com/firebasejs/11.0.2/firebase-app.js';
import {getAuth,onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,signOut} from 'https://www.gstatic.com/firebasejs/11.0.2/firebase-auth.js';
import {getFirestore,collection,doc,setDoc,getDoc,addDoc,updateDoc,deleteDoc,onSnapshot,query,orderBy,serverTimestamp,limit} from 'https://www.gstatic.com/firebasejs/11.0.2/firebase-firestore.js';
import {firebaseConfig} from './firebase-config.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);let me=null,currentRoom=null,unsubRooms=null,unsubMembers=null,unsubMessages=null,stream=null,songs=[],songIndex=-1,audio=new Audio();
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function msg(t){$('authMsg').textContent=t}
$('signIn').onclick=async()=>{try{await signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value)}catch(e){msg(e.message)}};
$('signUp').onclick=async()=>{try{const c=await createUserWithEmailAndPassword(auth,$('email').value.trim(),$('password').value);await setDoc(doc(db,'profiles',c.user.uid),{uid:c.user.uid,username:$('username').value.trim()||'User',gender:'',createdAt:serverTimestamp()});}catch(e){msg(e.message)}};
$('signOut').onclick=()=>signOut(auth);onAuthStateChanged(auth,async u=>{me=u;if(u){$('auth').hidden=true;$('main').hidden=false;await loadProfile();listenRooms()}else{$('auth').hidden=false;$('main').hidden=true;closeRoom()}});
async function loadProfile(){const s=await getDoc(doc(db,'profiles',me.uid));const p=s.exists()?s.data():{username:me.email.split('@')[0]};$('myName').textContent=p.username||'User';$('myGender').textContent=p.gender||'Member';$('myId').textContent=me.uid.slice(0,10);$('myAvatar').textContent=(p.username||'U').slice(0,2).toUpperCase()}
function listenRooms(){unsubRooms?.();unsubRooms=onSnapshot(collection(db,'rooms'),s=>{$('roomList').innerHTML='';s.forEach(d=>{const r=d.data();$('roomList').insertAdjacentHTML('beforeend',`<button class="room-card" data-room="${d.id}"><div class="room-avatar">${esc((r.name||'R').slice(0,2).toUpperCase())}</div><div><b>${esc(r.name||'Room')}</b><small>👥 ${r.memberCount||0} people</small></div><span>›</span></button>`)});document.querySelectorAll('[data-room]').forEach(x=>x.onclick=()=>openRoom(x.dataset.room))})}
$('createRoom').onclick=async()=>{const name=prompt('Room name','My Vibes Room');if(!name)return;const r=await addDoc(collection(db,'rooms'),{name,ownerId:me.uid,memberCount:1,createdAt:serverTimestamp()});await setDoc(doc(db,'rooms',r.id,'members',me.uid),{uid:me.uid,username:$('myName').textContent,role:'host',joinedAt:serverTimestamp()});openRoom(r.id)};
async function openRoom(id){currentRoom=id;$('roomsView').hidden=true;$('profileCard').hidden=true;$('roomView').hidden=false;const r=await getDoc(doc(db,'rooms',id));$('roomTitle').textContent=r.data()?.name||'Room';unsubMembers?.();unsubMessages?.();unsubMembers=onSnapshot(collection(db,'rooms',id,'members'),s=>{const a=[];s.forEach(d=>a.push(d.data()));renderSeats(a,r.data()?.ownerId)});const q=query(collection(db,'rooms',id,'messages'),orderBy('createdAt','asc'),limit(100));unsubMessages=onSnapshot(q,s=>{$('messages').innerHTML='';s.forEach(d=>{const m=d.data();$('messages').insertAdjacentHTML('beforeend',`<div class="chat"><b>${esc(m.username||'User')}</b> ${esc(m.text||'')}</div>`)});$('messages').scrollTop=$('messages').scrollHeight})}
function renderSeats(members,owner){$('roomCount').textContent=`${members.length} people`;const seats=[...members];while(seats.length<8)seats.push(null);$('seats').innerHTML=seats.slice(0,8).map((m,i)=>m?`<button class="seat" data-user="${esc(m.uid)}"><div class="seat-avatar">${esc((m.username||'U').slice(0,2).toUpperCase())}</div><small>${m.uid===owner?'👑 ':''}${esc(m.username||'User')}</small></button>`:`<div class="seat empty"><div class="seat-avatar">＋</div><small>Empty</small></div>`).join('');document.querySelectorAll('.seat[data-user]').forEach(b=>b.onclick=()=>showUserMenu(b.dataset.user,owner))}
async function showUserMenu(uid,owner){const snap=await getDoc(doc(db,'rooms',currentRoom,'members',uid));const p=snap.data()||{};const isHost=me.uid===owner;$('modalRoot').innerHTML=`<div class="overlay" id="overlay"><div class="sheet"><button class="close" onclick="document.getElementById('overlay').remove()">×</button><div class="big-avatar">${esc((p.username||'U').slice(0,2).toUpperCase())}</div><h3>${esc(p.username||'User')}</h3><p>ID: ${esc(uid.slice(0,10))}</p><button data-host="seat">🪑 Seat Here</button><button data-host="mute">🔇 Mute</button><button data-host="unmute">🔊 Unmute</button><button data-host="like">❤️ Like</button>${isHost?`<button class="danger" data-host="kick">👢 Kick Out</button><button class="danger" data-host="block">🚫 Block</button>`:''}<button data-host="profile">👤 View Profile</button></div></div>`;document.querySelectorAll('[data-host]').forEach(b=>b.onclick=()=>hostAction(b.dataset.host,uid,p.username||'User',owner))}
async function hostAction(action,uid,name,owner){document.getElementById('overlay')?.remove();if(action==='like'){alert(`❤️ Liked ${name}`);return}if(me.uid!==owner){alert('Only the room host can use host controls.');return}if(action==='kick'||action==='block'){await deleteDoc(doc(db,'rooms',currentRoom,'members',uid));return}alert(`${action} applied to ${name}`)}
$('sendMessage').onclick=sendMessage;$('messageInput').onkeydown=e=>{if(e.key==='Enter')sendMessage()};async function sendMessage(){const t=$('messageInput').value.trim();if(!t||!currentRoom)return;await addDoc(collection(db,'rooms',currentRoom,'messages'),{uid:me.uid,username:$('myName').textContent,text:t,createdAt:serverTimestamp()});$('messageInput').value=''}
$('micBtn').onclick=async()=>{try{if(stream){stream.getTracks().forEach(t=>t.stop());stream=null;$('micBtn').textContent='🎙️';return}stream=await navigator.mediaDevices.getUserMedia({audio:true});$('micBtn').textContent='🔴';}catch(e){alert('Microphone permission is required for voice.')}};
$('audioPicker').onchange=e=>{songs=[...e.target.files].map(file=>({name:file.name,url:URL.createObjectURL(file)}));songIndex=songs.length?0:-1;if(songs.length)playSong()};function playSong(){if(songIndex<0)return;audio.src=songs[songIndex].url;audio.play();showMusic()};function showMusic(){const list=songs.map((s,i)=>`<button class="song" data-song="${i}">🎵 ${esc(s.name)}</button>`).join('');$('modalRoot').innerHTML=`<div class="overlay" id="musicOverlay"><div class="sheet"><button class="close" onclick="document.getElementById('musicOverlay').remove()">×</button><h3>🎵 My Music</h3><p>Choose songs stored on your phone.</p><button id="pickAgain">＋ Add songs</button><div>${list||'<p>No songs selected.</p>'}</div><div class="player"><button id="prevSong">⏮</button><button id="playPause">▶/⏸</button><button id="nextSong">⏭</button></div></div></div>`;$('pickAgain').onclick=()=>$('audioPicker').click();document.querySelectorAll('[data-song]').forEach(b=>b.onclick=()=>{songIndex=+b.dataset.song;playSong()});$('prevSong').onclick=()=>{if(!songs.length)return;songIndex=(songIndex-1+songs.length)%songs.length;playSong()};$('nextSong').onclick=()=>{if(!songs.length)return;songIndex=(songIndex+1)%songs.length;playSong()};$('playPause').onclick=()=>audio.paused?audio.play():audio.pause()}
function closeRoom(){currentRoom=null;unsubMembers?.();unsubMessages?.();$('roomView').hidden=true;if(me){$('roomsView').hidden=false;$('profileCard').hidden=false}}
function doAction(a){const actions={search:()=>alert('Search users and rooms'),rankings:()=>alert('Rankings coming from room activity'),friends:()=>alert('Friends'),games:()=>alert('Games'),profile:()=>alert('Profile editor'),store:()=>alert('My Store'),backpack:()=>alert('Backpack'),referral:()=>alert('Referral'),host:()=>alert('Host Center'),level:()=>alert('Level'),help:()=>alert('Help & Safety'),settings:()=>alert('Settings'),copyId:()=>navigator.clipboard?.writeText(me.uid),speaker:()=>alert('Speaker control'),music:()=>$('audioPicker').click(),emoji:()=>{$('messageInput').value+=' ❤️'},closeRoom,share:()=>navigator.share?.({title:'.vibes',text:'Join my .vibes room'}),roomMore:()=>alert('Room options')};actions[a]?.()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)doAction(b.dataset.action)});
